<a href="https://colab.research.google.com/github/william132486486/william132486486/blob/main/Z_score%E6%AA%94.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import pandas as pd

In [6]:
url = "https://raw.githubusercontent.com/william132486486/william132486486/main/balance-sheet.csv"

In [7]:
df1 = pd.read_csv(url, index_col=0, encoding='unicode_escape')

In [8]:
df1

,YYYY/MM,Quarter,consolidation,Month,Currency,Total cash and cash equivalents,Total current financial assets at fair value through profit or loss,Financial assets at fair value through other comprehensive income - Current,Financial assets measured at amortized cost - Current,Current financial assets for hedging,...,Total other equity interest,Treasury shares,Total equity attributable to owners of parent,Interests in the former associate or jointly controlled entity,Non-controlling interest in pre-acquisition share capital,Non-controlling interests,Total equity,Total liabilities & equity,Unnamed: 112,Unnamed: 113
CO_ID,,,,,,,,,,,,,,,,,,,,,
1103 CHC,2023/12,4.0,Y,12.0,NTD,2054339.0,1435732.0,2478000.0,3945242.0,0.0,...,3280168.0,(1077950.00),21681451.0,0.0,0.0,737107.0,22418558.0,36464334.0,NaN,NaN
1104 UCC,2023/12,4.0,Y,12.0,NTD,1418310.0,13972.0,2691567.0,127350.0,0.0,...,807552.0,0.00,21869182.0,0.0,0.0,808952.0,22678134.0,28189560.0,NaN,NaN
NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
url = "https://raw.githubusercontent.com/william132486486/william132486486/main/Income%20statement.csv"

In [10]:
df2 = pd.read_csv(url, index_col=0, encoding='unicode_escape')

In [21]:
df2

,YYYY/MM,Quarter,consolidation,Month,Currency,Gross operating revenue,Total rental revenue,Operating revenue - Disposal of lands,Interest revenue,Operating revenue - disposal of investments,...,Diluted net income,Total diluted earnings per share,Average diluted common shares (Thousand),Earnings before interest and tax,"Earnings before interest, tax, depreciation and amortization",Recurring net income,Treasury shares-buys back,Treasury shares-subsidiary holding,Total treasury shares,Unnamed: 134
CO_ID,,,,,,,,,,,,,,,,,,,,,
1103 CHC,2023/12,4.0,Y,12.0,NTD,2620576.0,291007.0,0.0,0.0,0.0,...,81082.0,0.12,658931.0,286486.0,745243.0,139108.0,1435.0,129918.0,131353.0,NaN
1104 UCC,2023/12,4.0,Y,12.0,NTD,7802362.0,0.0,0.0,0.0,0.0,...,2107758.0,3.12,675018.0,2638263.0,2824162.0,1807985.0,0.0,0.0,0.0,NaN
NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [22]:
df1.columns

Index(['YYYY/MM', 'Quarter', 'consolidation', 'Month', 'Currency',
       'Total cash and cash equivalents',
       'Total current financial assets at fair value through profit or loss',
       'Financial assets at fair value through other comprehensive income - Current',
       'Financial assets measured at amortized cost - Current',
       'Current financial assets for hedging',
       ...
       'Total other equity interest', 'Treasury shares',
       'Total equity attributable to owners of parent',
       'Interests in the former associate or jointly controlled entity',
       'Non-controlling interest in pre-acquisition share capital',
       'Non-controlling interests', 'Total equity',
       'Total liabilities & equity', 'Unnamed: 112', 'Unnamed: 113'],
      dtype='object', length=113)

In [13]:
df2.columns

Index(['YYYY/MM', 'Quarter', 'consolidation', 'Month', 'Currency',
       'Gross operating revenue', 'Total rental revenue',
       'Operating revenue - Disposal of lands', 'Interest revenue',
       'Operating revenue - disposal of investments',
       ...
       'Diluted net income', 'Total diluted earnings per share',
       'Average diluted common shares (Thousand)',
       'Earnings before interest and tax',
       'Earnings before interest, tax, depreciation and amortization',
       'Recurring net income', 'Treasury shares-buys back',
       'Treasury shares-subsidiary holding', 'Total treasury shares',
       'Unnamed: 134'],
      dtype='object', length=134)

In [23]:
df1.index

Index(['1103 CHC', '1104 UCC', nan, nan, nan, nan, nan, nan, nan, nan], dtype='object', name='CO_ID')

In [24]:
df2.index

Index(['1103 CHC', '1104 UCC', nan, nan, nan], dtype='object', name='CO_ID')

In [25]:
A_1103 = (df1.loc['1103 CHC','Total current assets'] - df1.loc['1103 CHC','Total current liabilities'])/df1.loc['1103 CHC','Total assets']

In [26]:
A_1103

0.19875072995985613

In [27]:
X1 ='Total current assets'
X2 ='Total current liabilities'
X3 ='Total assets'
X4 ='Total retained earnings'
X5 ='Earnings before interest and tax'
X6 ='Total equity'
X7 ='Total liabilities'
X8 ='Total operating revenue'
CHC ='1103 CHC'
UCC ='1104 UCC'

In [28]:
A_CHC = (df1.loc[CHC,X1] - df1.loc[CHC,X2])/df1.loc[CHC,X3]

In [29]:
B_CHC = df1.loc[CHC,X4]/df1.loc[CHC, X3]

In [30]:
C_CHC = df2.loc[CHC,X5]/df1.loc[CHC, X3]

In [31]:
D_CHC = df1.loc[CHC,X6]/df1.loc[CHC, X7]  #調整分子項定義，採用股東權益帳面價值

In [32]:
E_CHC = df2.loc[CHC,X8]/df1.loc[CHC, X3]

In [33]:
Z_score_CHC = 1.2*A_CHC + 1.4*B_CHC + 3.3*C_CHC + 0.6*D_CHC+1.0*E_CHC

In [34]:
Z_score_CHC, A_CHC, B_CHC, C_CHC, D_CHC, E_CHC

(1.6958037287032623,
 0.19875072995985613,
 0.2813318351022125,
 0.007856608597321426,
 1.5961067583592392,
 0.07984742022163356)

In [35]:
A_UCC = (df1.loc[UCC,X1] - df1.loc[UCC,X2])/df1.loc[UCC,X3]

In [36]:
B_UCC = df1.loc[UCC,X4]/df1.loc[UCC, X3]

In [37]:
C_UCC = df2.loc[UCC,X5]/df1.loc[UCC, X3]

In [38]:
D_UCC = df1.loc[UCC,X6]/df1.loc[UCC, X7]  #調整分子項定義，採用股東權益帳面價值

In [39]:
E_UCC = df2.loc[UCC,X8]/df1.loc[UCC, X3]

In [40]:
Z_score_UCC = 1.2*A_UCC + 1.4*B_UCC + 3.3*C_UCC + 0.6*D_UCC+1.0*E_UCC

In [41]:
Z_score_UCC, A_UCC, B_UCC, C_UCC, D_UCC, E_UCC

(3.877376542351587,
 0.09782291742049185,
 0.5039360671113703,
 0.09359007377199219,
 4.114748887130118,
 0.27678197176543373)